apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
  - name: goldilocks
    version: 10.3.0
    repo: https://charts.fairwinds.com/stable
    releaseName: goldilocks
    namespace: goldilocks
    valuesFile: values.yaml
    valuesMerge: override
    additionalValuesFiles:
      - overrides.yaml