apiVersion: v1
data:
  type: Z2l0
  url: aHR0cHM6Ly9naXRodWIuY29tL21yYTg5L2FyZ29jZC1kZW1vLmdpdA==
kind: Secret
metadata:
  labels:
    argocd.argoproj.io/secret-type: repository
  name: local
  namespace: argocd
type: Opaque